baseURL = "https://daiji256.github.io/"
title = "Daiji Blog"
author = "Daiji"
theme = "hugo-clean-blog"
canonifyurls = true
copyright = "© 2020–2022 Daiji Blog"
paginate = 8
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
enableGitInfo = true
hasCJKLanguage = true
summaryLength = 96
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
assetDir = "static"
timeout = 100000

[taxonomies]
    category = "categories"
    tag = "tags"

[markup]
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 5
        ordered = false
    [markup.highlight]
        linenos=true
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
