baseURL = "https://daiji256.github.io/"
title = "Daiji Blog"
author = "Daiji"
theme = "hugo-clean-blog"
publishDir = "docs"
canonifyurls = true
copyright = "© 2020–2021 Daiji - Powered by GitHub Pages & Hugo."
paginate = 8
languageCode = "ja"
DefaultContentLanguage = "ja"
disqusShortname = "daiji256-github-io"
enableInlineShortcodes = true
hasCJKLanguage = true
summaryLength = 96
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
author = "Daiji"
authorInfo = "ずっとパソコンの前でだらだらしている高専生です。いっぱい記事を書いていきたいと思ってます。"

[taxonomies]
category = "categories"
tag = "tags"

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 5
ordered = false
