baseURL = "https://butty256.github.io/"
title = "Butty Blog"
theme = "hugo-mycoder"
publishDir = "docs"
canonifyurls = true
languageCode = "ja"
defaultContentLanguage = "ja"
paginate = 10
pygmentsStyle = "native"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Butty256"
description = "Butty Blog"
keywords = "blog, note"
info = "Daiji Suzuki"
avatarURL = "images/icon.png"
footerContent = ""
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2021
commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
enableTwemoji = false
customCSS = [
	"https://fonts.googleapis.com/css?family=Roboto",
	"http://fonts.googleapis.com/earlyaccess/notosansjp.css",
	"https://fonts.googleapis.com/css?family=Roboto+Mono",
	"https://fonts.googleapis.com/css2?family=M+PLUS+1p"
]
customSCSS = []
customJS = []

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "GitHub"
icon = "icon github"
weight = 1
url = "https://github.com/Butty256/"

[[params.social]]
name = "Twitter"
icon = "icon twitter"
weight = 2
url = "https://twitter.com/butty256/"

[[params.social]]
name = "Qiita"
icon = "icon qiita"
weight = 3
url = "https://qiita.com/Butty256/"

[languages.ja]
languageName = ":japan:"

[[languages.ja.menu.main]]
name = "Home"
weight = 1
url = ""

[[languages.ja.menu.main]]
name = "Tags"
weight = 2
url = "tags/"

[[languages.ja.menu.main]]
name = "Categories"
weight = 3
url = "categories/"

[[languages.ja.menu.main]]
name = "About me"
weight = 4
url = "aboutme/"
